upstream-config:
  upstreams:
    - id: eth-upstream
      chain: ethereum
      rate-limit:
        auto: true
        rules:
          - method: eth_getBlockByNumber
            requests: 100
            period: 1s
      connectors:
        - type: json-rpc
          url: https://test.com
