server:
  port: 9095

rate-limit:
  - budgets:
      - name: standard-budget
        config:
          rules:
            - method: eth_getBlockByNumber
              requests: 100
              period: 1s
      - name: premium-budget
        config:
          rules:
            - method: eth_call
              requests: 500
              period: 1s

upstream-config:
  upstreams:
    - id: eth-upstream
      chain: ethereum
      rate-limit-budget: standard-budget
      connectors:
        - type: json-rpc
          url: https://test.com
