apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}-config
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
  annotations:
    checksum/nodecore-config: {{ .Values.nodecoreConfig | toJson | sha256sum }}
type: Opaque
data:
  nodecore.yaml: {{ toYaml .Values.nodecoreConfig | b64enc | quote }}
