apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}-ssl
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.nodecoreSSL }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
