apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}-env
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.serviceEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
