apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
spec: 
  type: {{ .Values.service.type }}
  ports:
  - name: app
    port: 9095
    targetPort: 9095
    protocol: TCP
  - name: metrics
    port: 9093
    targetPort: 9093
    protocol: TCP
  - name: health
    port: 9096
    targetPort: 9096
    protocol: TCP
  selector:
    {{- include "k8s.selectorLabels" . | nindent 4 }}
