name: Run tests

on:
  workflow_dispatch: null
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use"
        required: false
        type: string
        default: "1.25.5"
  pull_request:
    paths-ignore:
      - 'chart/**'
      - 'chart/nodecore/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'chart/**'
      - 'chart/nodecore/**'

env:
  GO_VERSION: ${{ inputs.go-version || '1.25.5' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Go project
        uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-key-suffix: "test"

      - name: Run tests
        run: make test
