server:
  port: 9095

app-storages:
  - name: redis-storage
    type: redis
    redis:
      address: localhost:6379

rate-limit-budgets:
  engines:
    - name: memory
      type: memory
    - name: redis
      type: redis
      redis:
        storage-name: redis-storage
  budgets:
    - default-engine: memory
      budgets:
        - name: memory-budget
          config:
            rules:
              - method: eth_call
                requests: 100
                period: 1s
        - name: redis-budget
          engine: redis
          config:
            rules:
              - method: eth_getBalance
                requests: 200
                period: 1s

upstream-config:
  upstreams:
    - id: eth-upstream
      chain: ethereum
      connectors:
        - type: json-rpc
          url: https://test.com
