server:
  port: 9095

rate-limit-budgets:
  engines:
    - name: ""
      type: memory
  budgets:
    - default-engine: memory
      budgets:
        - name: test-budget
          config:
            rules:
              - method: eth_call
                requests: 100
                period: 1s

upstream-config:
  upstreams:
    - id: eth-upstream
      chain: ethereum
      connectors:
        - type: json-rpc
          url: https://test.com
