server:
  port: 9095

rate-limit-budgets:
  budgets:
    - budgets:
        - name: test-budget
          engine: nonexistent-engine
          config:
            rules:
              - method: eth_call
                requests: 100
                period: 1s

upstream-config:
  upstreams:
    - id: eth-upstream
      chain: ethereum
      connectors:
        - type: json-rpc
          url: https://test.com
