upstream-config:
  upstreams:
    - id: eth-upstream
      chain: ethereum
      connectors:
        - type: json-rpc
          url: https://test.com
      options:
        internal-timeout: 5s
        validation-interval: 30s
        disable-validation: true
        disable-settings-validation: true
        disable-chain-validation: true
