server:
  port: 9095

app-storages:
  - name: redis-storage
    type: redis
    redis:
      address: localhost:6379

rate-limit-budgets:
  engines:
    - name: redis
      type: redis
      redis:
        storage-name: redis-storage
  budgets:
    - default-engine: redis
      budgets:
        - name: redis-budget
          config:
            rules:
              - method: eth_getBlockByNumber
                requests: 100
                period: 1s

upstream-config:
  upstreams:
    - id: eth-upstream
      chain: ethereum
      rate-limit-budget: redis-budget
      connectors:
        - type: json-rpc
          url: https://test.com
